"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation";
import { Header } from "@/widgets/pageLayout";
import "./assets/css/globals.css";
import "./assets/css/basic.css";
import "./assets/css/layout.css";
import "./assets/css/dashboard.css";
import "./assets/css/searchInput.css";
import "./assets/css/incomeStatementTable.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // 헤더를 숨길 경로들
  const hiddenHeaderPaths = ["/login", "/signup"];

  const showHeader = !hiddenHeaderPaths.includes(pathname);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {showHeader && <Header />}
        <main className={showHeader ? "pt-[56px]" : ""}>{children}</main>
      </body>
    </html>
  );
}
